//
//  MockUserRepository.swift
//  MVVMExampleTests
//
//  Created by Nick Todd on 23/10/2025.
//

import Foundation
import Cuckoo
@testable import MVVMExample

/**
 * MOCK USER REPOSITORY USING CUCKOO
 *
 * This file demonstrates advanced mocking techniques using Cuckoo framework.
 * 
 * Key benefits of using Cuckoo for mocking:
 * 1. TYPE SAFETY: Compile-time verification of mock setup
 * 2. ARGUMENT MATCHING: Flexible argument matching (any(), exact values, custom matchers)
 * 3. VERIFICATION: Verify method calls, call counts, and argument values
 * 4. STUBBING: Control return values and behavior of mocked methods
 * 5. SPYING: Partial mocks that can call through to real implementations when needed
 *
 * Mock Usage Patterns:
 * - stub(): Define what the mock should return
 * - verify(): Assert that methods were called as expected
 * - ArgumentCaptor: Capture arguments passed to methods for assertion
 * - any(): Match any argument of the correct type
 * - times(): Verify specific number of method calls
 */

// MARK: - Generated Mock Class

/**
 * This mock would typically be generated by Cuckoo's code generation,
 * but for demonstration purposes, we're implementing it manually.
 * 
 * In a real project, you would:
 * 1. Add a build phase to run Cuckoo's generator
 * 2. Annotate protocols with //MARK: - AutoMockable
 * 3. Let Cuckoo generate this code automatically
 */
class MockUserRepository: UserRepositoryProtocol, Mock {
    
    // MARK: - Cuckoo Infrastructure
    
    var cuckoo_manager = CuckooManager()
    
    // MARK: - Protocol Implementation
    
    func getAllUsers() -> [User] {
        return cuckoo_manager.call(
            "getAllUsers() -> [User]",
            parameters: (),
            escapingParameters: ()
        ) as [User]
    }
    
    func getUserById(_ id: Int) -> User? {
        return cuckoo_manager.call(
            "getUserById(Int) -> User?",
            parameters: (id),
            escapingParameters: (id)
        ) as User?
    }
    
    func addUser(_ user: User) -> User {
        return cuckoo_manager.call(
            "addUser(User) -> User",
            parameters: (user),
            escapingParameters: (user)
        ) as User
    }
    
    func deleteUser(withId id: Int) -> Bool {
        return cuckoo_manager.call(
            "deleteUser(withId: Int) -> Bool",
            parameters: (id),
            escapingParameters: (id)
        ) as Bool
    }
    
    func updateUser(_ user: User) -> User? {
        return cuckoo_manager.call(
            "updateUser(User) -> User?",
            parameters: (user),
            escapingParameters: (user)
        ) as User?
    }
}

// MARK: - Mock Extensions for Easier Testing

extension MockUserRepository {
    
    /**
     * CONVENIENCE STUBBING METHODS
     * 
     * These methods make it easier to set up common mock scenarios
     * without having to write verbose stub() calls in every test
     */
    
    /// Sets up the mock to return an empty user list
    func stubEmptyUserList() {
        stub(self) { stub in
            when(stub.getAllUsers()).thenReturn([])
        }
    }
    
    /// Sets up the mock to return a predefined list of users
    func stubUserList(_ users: [User]) {
        stub(self) { stub in
            when(stub.getAllUsers()).thenReturn(users)
        }
    }
    
    /// Sets up the mock to successfully add any user and return it with a new ID
    func stubSuccessfulUserAdd(withId newId: Int = 1) {
        stub(self) { stub in
            when(stub.addUser(any())).then { user in
                return User(id: newId, name: user.name)
            }
        }
    }
    
    /// Sets up the mock to successfully delete any user
    func stubSuccessfulUserDelete() {
        stub(self) { stub in
            when(stub.deleteUser(withId: any())).thenReturn(true)
        }
    }
    
    /// Sets up the mock to fail user deletion
    func stubFailedUserDelete() {
        stub(self) { stub in
            when(stub.deleteUser(withId: any())).thenReturn(false)
        }
    }
    
    /// Sets up the mock to return a specific user by ID
    func stubUserById(_ user: User) {
        stub(self) { stub in
            when(stub.getUserById(user.id)).thenReturn(user)
        }
    }
    
    /// Sets up the mock to return nil for any user ID lookup
    func stubUserNotFound() {
        stub(self) { stub in
            when(stub.getUserById(any())).thenReturn(nil)
        }
    }
}

// MARK: - Test Scenarios Helper

/**
 * TEST SCENARIO BUILDER
 *
 * This class helps create common test scenarios quickly.
 * It demonstrates the Builder pattern for test setup.
 */
class MockRepositoryScenario {
    private let mock: MockUserRepository
    
    init(mock: MockUserRepository) {
        self.mock = mock
    }
    
    /// Scenario: Empty repository
    func emptyRepository() -> MockRepositoryScenario {
        mock.stubEmptyUserList()
        return self
    }
    
    /// Scenario: Repository with sample users
    func withSampleUsers() -> MockRepositoryScenario {
        mock.stubUserList(User.mockUsers())
        return self
    }
    
    /// Scenario: Repository that successfully handles all operations
    func successfulOperations() -> MockRepositoryScenario {
        mock.stubUserList([])
        mock.stubSuccessfulUserAdd()
        mock.stubSuccessfulUserDelete()
        return self
    }
    
    /// Scenario: Repository that fails operations (for error testing)
    func failingOperations() -> MockRepositoryScenario {
        mock.stubEmptyUserList()
        mock.stubFailedUserDelete()
        mock.stubUserNotFound()
        return self
    }
    
    func build() -> MockUserRepository {
        return mock
    }
}

// MARK: - Mock Factory

/**
 * MOCK FACTORY
 *
 * Provides convenient factory methods for creating mocks with common configurations
 */
struct MockUserRepositoryFactory {
    
    /// Creates a mock with empty user list
    static func createEmpty() -> MockUserRepository {
        let mock = MockUserRepository()
        _ = MockRepositoryScenario(mock: mock).emptyRepository()
        return mock
    }
    
    /// Creates a mock with sample users
    static func createWithSampleUsers() -> MockUserRepository {
        let mock = MockUserRepository()
        _ = MockRepositoryScenario(mock: mock).withSampleUsers()
        return mock
    }
    
    /// Creates a mock that handles all operations successfully
    static func createSuccessful() -> MockUserRepository {
        let mock = MockUserRepository()
        _ = MockRepositoryScenario(mock: mock).successfulOperations()
        return mock
    }
    
    /// Creates a mock that fails operations (for error testing)
    static func createFailing() -> MockUserRepository {
        let mock = MockUserRepository()
        _ = MockRepositoryScenario(mock: mock).failingOperations()
        return mock
    }
}